"""update constraint

Revision ID: 05a6c3b654f1
Revises: c403c657f93d
Create Date: 2021-01-22 16:21:23.131766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a6c3b654f1'
down_revision = 'c403c657f93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_agent_user', 'reservation', ['r_user', 'agent'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_agent_user', 'reservation', type_='unique')
    # ### end Alembic commands ###
