"""Changing column name for Reservation user

Revision ID: 2d3179287717
Revises: 9a27b750155b
Create Date: 2021-01-22 11:42:42.996982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3179287717'
down_revision = '9a27b750155b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('ruser', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'username')
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('reservation', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    op.drop_column('reservation', 'ruser')
    # ### end Alembic commands ###
