"""add table reservation

Revision ID: 2f5a115ed4bb
Revises: 396934f13b2a
Create Date: 2021-01-22 12:35:30.511025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5a115ed4bb'
down_revision = '396934f13b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('r_user', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent')
    )
    op.create_index(op.f('ix_reservation_timestamp'), 'reservation', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_timestamp'), table_name='reservation')
    op.drop_table('reservation')
    # ### end Alembic commands ###
