"""drop table reservation

Revision ID: 396934f13b2a
Revises: 90ce9b0eeb69
Create Date: 2021-01-22 12:32:49.315384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396934f13b2a'
down_revision = '90ce9b0eeb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservation_timestamp', table_name='reservation')
    op.drop_table('reservation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent', sa.VARCHAR(length=32), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ruser', sa.VARCHAR(length=64), nullable=True),
    sa.Column('r_user', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent')
    )
    op.create_index('ix_reservation_timestamp', 'reservation', ['timestamp'], unique=False)
    # ### end Alembic commands ###
