"""update env column

Revision ID: 6c4568ac3e94
Revises: cf0788f0ed98
Create Date: 2021-01-23 11:31:43.564430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4568ac3e94'
down_revision = 'cf0788f0ed98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('env', sa.String(length=250), nullable=True))
    op.drop_constraint('unique_agent_user', 'reservation', type_='unique')
    op.create_unique_constraint('unique_agent_user', 'reservation', ['r_user', 'env'])
    op.drop_column('reservation', 'agent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('agent', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint('unique_agent_user', 'reservation', type_='unique')
    op.create_unique_constraint('unique_agent_user', 'reservation', ['r_user', 'agent'])
    op.drop_column('reservation', 'env')
    # ### end Alembic commands ###
