"""drop reservation

Revision ID: 81414b23c408
Revises: 2f5a115ed4bb
Create Date: 2021-01-22 12:38:32.136337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81414b23c408'
down_revision = '2f5a115ed4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservation_timestamp', table_name='reservation')
    op.drop_table('reservation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent', sa.VARCHAR(length=32), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('r_user', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent')
    )
    op.create_index('ix_reservation_timestamp', 'reservation', ['timestamp'], unique=False)
    # ### end Alembic commands ###
