"""updating reservation table

Revision ID: 9a27b750155b
Revises: a5197f8181e4
Create Date: 2021-01-22 10:49:47.144705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a27b750155b'
down_revision = 'a5197f8181e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    op.drop_column('reservation', 'username')
    # ### end Alembic commands ###
