"""changing unique constraint and change user column

Revision ID: a11bd4d605dd
Revises: d98a768d7e79
Create Date: 2021-01-22 12:25:48.072352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11bd4d605dd'
down_revision = 'd98a768d7e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('r_user', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'user_id')
    op.drop_column('reservation', 'ruser')
    op.drop_column('reservation', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('reservation', sa.Column('ruser', sa.VARCHAR(length=64), nullable=True))
    op.add_column('reservation', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    op.drop_column('reservation', 'r_user')
    # ### end Alembic commands ###
