"""add constraint

Revision ID: c403c657f93d
Revises: 27c2177a32b5
Create Date: 2021-01-22 16:06:39.853997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c403c657f93d'
down_revision = '27c2177a32b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reservation', ['agent', 'r_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='unique')
    # ### end Alembic commands ###
