"""add Agentprofile table

Revision ID: cf0788f0ed98
Revises: a4df8dbf9373
Create Date: 2021-01-23 11:29:55.318700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0788f0ed98'
down_revision = 'a4df8dbf9373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_name', sa.String(length=64), nullable=True),
    sa.Column('a_user', sa.String(length=64), nullable=True),
    sa.Column('a_pass', sa.String(length=64), nullable=True),
    sa.Column('a_serial', sa.String(length=64), nullable=True),
    sa.Column('a_access', sa.String(length=64), nullable=True),
    sa.Column('a_env', sa.String(length=250), nullable=True),
    sa.Column('a_duration', sa.Integer(), nullable=True),
    sa.Column('a_owner', sa.String(length=64), nullable=True),
    sa.Column('a_last_reserved', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_index(op.f('ix_agent_profile_a_last_reserved'), 'agent_profile', ['a_last_reserved'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_profile_a_last_reserved'), table_name='agent_profile')
    op.drop_table('agent_profile')
    # ### end Alembic commands ###
