"""first model

Revision ID: d77d491a30f9
Revises: 
Create Date: 2021-01-26 09:04:25.158924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77d491a30f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_name', sa.String(length=64), nullable=True),
    sa.Column('a_user', sa.String(length=64), nullable=True),
    sa.Column('a_pass', sa.String(length=64), nullable=True),
    sa.Column('a_serial', sa.String(length=64), nullable=True),
    sa.Column('a_access', sa.String(length=64), nullable=True),
    sa.Column('a_env', sa.String(length=250), nullable=True),
    sa.Column('a_ipaddr', sa.String(length=32), nullable=True),
    sa.Column('a_location', sa.String(length=64), nullable=True),
    sa.Column('a_command_line', sa.String(length=32), nullable=True),
    sa.Column('a_duration', sa.Integer(), nullable=True),
    sa.Column('a_owner', sa.String(length=64), nullable=True),
    sa.Column('a_last_reserved', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_index(op.f('ix_agent_profile_a_last_reserved'), 'agent_profile', ['a_last_reserved'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('r_user', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('r_user', 'env', name='unique_agent_user')
    )
    op.create_index(op.f('ix_reservation_timestamp'), 'reservation', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reservation_timestamp'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_agent_profile_a_last_reserved'), table_name='agent_profile')
    op.drop_table('agent_profile')
    # ### end Alembic commands ###
