"""Changing column name for Reservation user

Revision ID: d98a768d7e79
Revises: 2d3179287717
Create Date: 2021-01-22 11:54:14.524819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98a768d7e79'
down_revision = '2d3179287717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'username')
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('reservation', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
