"""adding Task tables

Revision ID: ed8bd72e13cd
Revises: 8048fc90a615
Create Date: 2021-02-01 11:14:45.084297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed8bd72e13cd'
down_revision = '8048fc90a615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('a_name', table_name='agentprofile')
    op.drop_index('ix_agentprofile_a_last_reserved', table_name='agentprofile')
    op.drop_table('agentprofile')
    op.drop_table('followers')
    op.drop_index('ix_reservation_timestamp', table_name='reservation')
    op.drop_index('unique_agent_user', table_name='reservation')
    op.drop_table('reservation')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True),
    sa.Column('last_seen', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_table('reservation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('env', mysql.VARCHAR(collation='utf8_bin', length=250), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('r_user', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_agent_user', 'reservation', ['r_user', 'env'], unique=True)
    op.create_index('ix_reservation_timestamp', 'reservation', ['timestamp'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_ibfk_1'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_ibfk_2'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('agentprofile',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('a_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_user', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_pass', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_serial', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_access', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_env', mysql.VARCHAR(collation='utf8_bin', length=250), nullable=True),
    sa.Column('a_ipaddr', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('a_location', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_command_line', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.Column('a_duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('a_owner', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('a_last_reserved', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_agentprofile_a_last_reserved', 'agentprofile', ['a_last_reserved'], unique=False)
    op.create_index('a_name', 'agentprofile', ['a_name'], unique=True)
    # ### end Alembic commands ###
