"""update AgentProfile columns

Revision ID: fa09f87d8931
Revises: 6c4568ac3e94
Create Date: 2021-01-23 12:35:09.937618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa09f87d8931'
down_revision = '6c4568ac3e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_profile', sa.Column('a_command_line', sa.String(length=32), nullable=True))
    op.add_column('agent_profile', sa.Column('a_ipaddr', sa.String(length=32), nullable=True))
    op.add_column('agent_profile', sa.Column('a_location', sa.String(length=64), nullable=True))
    op.drop_constraint('unique_agent_user', 'reservation', type_='unique')
    op.create_unique_constraint('unique_agent_user', 'reservation', ['r_user', 'env'])
    op.drop_column('reservation', 'agent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('agent', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint('unique_agent_user', 'reservation', type_='unique')
    op.create_unique_constraint('unique_agent_user', 'reservation', ['r_user', 'agent'])
    op.drop_column('agent_profile', 'a_location')
    op.drop_column('agent_profile', 'a_ipaddr')
    op.drop_column('agent_profile', 'a_command_line')
    # ### end Alembic commands ###
